[project]
name = "mcp_rothi"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastmcp>=2.8.1",
    "jwt>=1.3.1",
    "pydantic>=2.11.5",
    "typing>=3.10.0.0",
]
